### ISSUE TITLE
Avoid copying dist files from /dist to libs/xxx/dist for lerna

### ISSUE THREAD

**Issue by yjaaidi** [jscutlery/convoyr#146]
Lerna needs `dist` files in directory relative to the package.
We are currently copying that package manually on prepublish. This is cumbersome and error prone.

Maybe we should configure that dist directory in `angular.json` (but we have to remember to do that again when we create new libs).

We could also just build the needed package in prepublish script instead of build everything with nx before.

**Comment by edbzn** [comment]
Contributing part should be updated according that.

**Comment by yjaaidi** [comment]
Oups! Forgot to add issue id in commit but here it is:
https://github.com/jscutlery/convoyr/commit/8585ddb67e604fca53b25a846a10c58f2c84cfcd
